export enum StatePostalCode {
  AZ, OH, WI
}
export enum ElectionType {
  PRESIDENTIAL,
  CONGRESSIONAL
}
export enum CandidateParty {
  DEM, REP, IND, GRN, LIB
}

export enum ErrorType {
  UNASSIGNED_AREA,
  OVERLAPPING,
  SELF_INTERSECTING,
  ENCLOSED_PRECINCT,
  MULTIPOLYGON,
  ZERO_POPULATION,
  ZERO_ELECTION_DATA,
  VOTE_NOT_PROPORTIONAL_TO_POP,
  MORE_VOTES_THAN_POP
}

export enum CorrectionType {
  POPULATION_DATA,
  ELECTION_DATA,
  GHOST_DESIGNATION,
  MERGE_PRECINCT,
  BOUNDARY_CHANGE,
  NEIGHBOR_CHANGE
}
